name: Publish NuGet package

on:
  # This enables manual trigger for the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    env:
      OUTPUT_DIR: package
    steps:

      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Build solution and generate NuGet package
        run: |  
          cd FeedReader
          dotnet pack -c Release -o ${{ env.OUTPUT_DIR }}

      - name: Find NuGet package
        id: find-package
        run: |
          PACKAGE_FILE=$(ls ${{ env.OUTPUT_DIR }}/*.nupkg)
          echo "PACKAGE_FILE=$PACKAGE_FILE" >> $GITHUB_ENV

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: latest
        
      - name: Push generated package to Nuget
        run: nuget push ${{ env.PACKAGE_FILE }} -Source https://api.nuget.org/v3/index.json
        